### ISSUE TITLE
Push git tags as docker tags

### ISSUE THREAD

**Issue by real34** [elgohr/Publish-Docker-Github-Action#24] opened 2019-09-20 21:32 UTC
Hi!

First of all, thanks for this great project. It works like a charm!

This is a feature request: being able to tag images with the git tag that was just pushed.

When pushing a tag (let's say `1.0.0`), it currently triggers 2 builds. The first one with the `GITHUB_REF` `/refs/head/master` and another one with `/refs/tags/1.0.0`.
Both are building and pushing an image tagged with `latest` (https://github.com/elgohr/Publish-Docker-Github-Action/blob/26842316386a364c913041bdf1536f392e63b945/entrypoint.sh#L26) since 215d3ea74449a6f7ebba746dd6d6fdfebcac4de6.

I think it could be great to build an image tagged as `1.0.0`, so users could update their instances by bumping the image version.

Do you think it would make sense?

**Comment by elgohr** [comment] 2019-09-21 07:26
Hey, thank you very much.
I'm totally with you. The only concern I have is, that there might be collisions between tags, releases and branches. 
When I'm thinking about releases/tags, I would like to freeze things to that moment.
A branch with the same name would override it.
In this way the tag for the only freezed state in this resource (snapshots) is autogenerated and very unlikely for a collision.
If you have a good idea for mitigating the collisions, I would be glad to hear it ☺️

**Comment by elgohr** [comment] 2019-09-23 18:46
Looks somehow like https://github.com/elgohr/Publish-Docker-Github-Action/issues/18
Do we want to keep the discussion in there?

**Comment by mrfelton** [comment] 2019-09-25 11:27
I'd prefer to see the image snapshots tagged using `GITHUB_SHA`. That way, we could reference the snapshot tag from other build jobs. As it is now, if you use the snapshot feature, there is no way to know what tag the image was assigned as so impossible to reuse the snapshot in other build jobs.

**Comment by elgohr** [comment] 2019-09-25 19:15
@mrfelton Find why it's not like this in https://github.com/elgohr/Publish-Docker-Github-Action/issues/13
What do you think about having the tag of the snapshot as an output?

**Comment by mrfelton** [comment] 2019-09-26 07:29
I think providing the snapshot name as an output would be pretty useful @elgohr

**Comment by real34** [comment] 2019-09-26 10:15
Thanks for this feedback. A solution could indeed be to have tag names such as `tag-1.0.0-GIT_SHA` (or date).

It would reduce the risk of collisions and allow to reduce the number of tags by not using the snapshot feature. Also users could easily find the image tag associated to a specific release.

**Comment by mrfelton** [comment] 2019-09-26 10:27
> A solution could indeed be to have tag names such as tag-1.0.0-GIT_SHA (or date).

That sounds like a possibility for tag builds, but what about branch based builds?

**Comment by mrfelton** [comment] 2019-09-26 11:16
Perhaps you could use something like this:
```
 --abbrev=40 --dirty
```

**Comment by mrfelton** [comment] 2019-09-26 11:16
Perhaps you could use something like this:
```
git describe --abbrev=40 --dirty
```

**Comment by elgohr** [comment] 2019-09-27 05:55
So what do you think about doing it like this:
| Types        | Tags                  |
|--------------|-----------------------|
| Tag          | latest, t-{UNIQUE_ID} |
| Release      | latest, r-{UNIQUE_ID} |
| Branch       | b-{UNIQUE_ID}         |
| Pull Request | p-{UNIQUE_ID}         |
(this table doesn't contain snapshot builds, which would stay like they are)
`UNIQUE_ID` would be the same like for snapshot builds.

**Comment by elgohr** [comment] 2019-09-27 06:13
Snapshot as outputs is here https://github.com/elgohr/Publish-Docker-Github-Action#outputs

**Comment by elgohr** [comment] 2019-10-08 19:30
No discussion within the last 12 days. I guess it's not that urgent. Can we close this?

**Comment by turbo** [comment] 2019-10-08 21:23
I too am looking for this functionality, what's the current state of this?

**Comment by elgohr** [comment] 2019-10-09 10:25
https://github.com/elgohr/Publish-Docker-Github-Action/issues/24#issuecomment-535798478 would be the proposal. Waiting for feedback

**Comment by real34** [comment] 2019-10-09 10:48
> [#24 (comment)](https://github.com/elgohr/Publish-Docker-Github-Action/issues/24#issuecomment-535798478) would be the proposal. Waiting for feedback

Hi! It would be a good compromise indeed.
Then running `docker tag my-image:GITHUB_SHA my-image:1.1.0` could be done manually with human control to prevent collisions.

Thanks for this solution, and sorry for not responding before.

**Comment by turbo** [comment] 2019-10-09 12:47
I don't know if I agree on explicitely tagging `latest`, though I may have misread something. What if two actions on two (say) releases are triggered and the first one finishes later? The release tags on the image will be correct, but now an older image is being tagged as `latest`?

**Comment by elgohr** [comment] 2019-10-09 18:20
Ok, then let's do it like that.

@turbo: sounds like an edgecase to me. 
At my point of view it would be an actions-feature for running parts of an action in serial.

**Comment by elgohr** [comment] 2019-10-10 20:17
@real34 just rethought a bit.
Couldn't you do the same, when you have `snapshots` enabled?
In the case of a Release/Tag this would be a push to master + a snapshoted tag.

**Comment by elgohr** [comment] 2019-10-10 20:21
@turbo please have a look at https://github.community/t5/GitHub-Actions/Prevent-parallel-workflows/m-p/32914/highlight/true#M1305

**Comment by turbo** [comment] 2019-10-15 12:51
@elgohr The root problem behind the scenario I've described is that your action would create the latest tag, not that Actions run concurrently. It's the reason other CI's docker actions (e.g. Azure DevOps) have a config option for "also tag `latest`". A release is a tag already, so I see no reason to *automatically* include the latest tag. If you do introduce this feature, it'd be nice if you made the latest tag an option. But don't let me hold you up from actually implementing this! After all, I can make my changes in a fork. :)

**Comment by elgohr** [comment] 2019-10-15 17:11
At the moment it doesn't look like this action needs any change, as you could get everything by configuration already.

**Comment by nicolas-marcq** [comment] 2019-10-17 08:44
Would it be possible to add a flag that allow us to choose the tag.
In our pipeline, we would like to always tag the dev branch 0.0.

**Comment by Sispheor** [comment] 2019-10-17 14:25
@elgohr so what kind of config should we use to have a tag that map the release number?

**Comment by elgohr** [comment] 2019-10-17 16:33
@sispheor sorry, this isn't possible as the action would need to handle collisions, which is way to complex.

**Comment by Sispheor** [comment] 2019-10-17 16:38
Where is the colision if we are sure to create a new tag?
Why we cannot use this?
```bash
elif isGitTag; then
    TAG=$(echo ${GITHUB_REF} | sed -e "s/refs\/tags\///g")
```

**Comment by elgohr** [comment] 2019-10-18 05:02
Sorry, I don't get what you're trying to do.
Could you please explain a little more?

**Comment by Sispheor** [comment] 2019-10-18 07:19
I think I want to do what is described in this issue.
When I git tag a version, this tag name is also used as docker tag when I build my image.

In the current code, if a git tag is detected like `refs/tags/5.0`, we don't tag with **5.0** but **latest**.
So I replaced the line 67 by the code I shown you and I have the expected behavior.

**Comment by elgohr** [comment] 2019-10-18 17:18
The point is, that branches with the same name as a release will override the release image and there would be no way to restore it. If you want to fix a point in time safely, feel free to use snapshots.

**Comment by turbo** [comment] 2019-10-18 17:26
> The point is, that branches with the same name as a release will override the release image

Not if the build is triggered on releaes, which is what would actually happen in production. Pushes to branches which happen to have the same name (e.g. from release management) fire separate events.

**Comment by Sispheor** [comment] 2019-10-18 17:28
a tag is seen with a ref that contains the word tags, isn't it? Like `refs/tags/5.0`.
Which is different from the ref we receive if it's a branch, right? The ref for a branch is like `/refs/head/branch_name`.

**Comment by elgohr** [comment] 2019-10-18 17:32
And all go into a registry, which doesn't care which job wrote what.

**Comment by elgohr** [comment] 2019-10-18 17:33
@turbo how would you ensure that a job, triggering on push, wouldn't override an image, which was pushed by a job that triggered on release?

**Comment by Sispheor** [comment] 2019-10-18 17:45
yes. But, from my point of view, pipelines need to be well configured to prevent overriding other images.
The expected behavior of this action is to map git tag to docker tag when exists.
In most of cases, the tag is a version number like 2.0 which doesn't conflit with branch names.

**Comment by elgohr** [comment] 2019-10-18 17:52
Sorry, that's your expectation.

At the moment we don't have the problem that people need to care for. And I don't think it's worth introducing, unless there is a usecase that couldn't be covered by using the current implementation.

**Comment by turbo** [comment] 2019-10-18 17:52
I wouldn't run any *publish* actions on push. Maybe run some tests, collect coverage etc. But for me at least, I wan't pretty much only tags to be "released". `latest` doesn't mean latest release, otherwise docker registry would attach it automatically to new pushes. It's meaning differs from project to project, sometimes it's a release, sometimes a beta and sometimes not used at all.

I think the best way to do this would be to:

- enable git tags as docker tags (explicit opt-in)
- state in the docs that for this use-case, the user has to make sure not to create conflicting triggers
- make "also tag `latest`" on *option* for the action, regardless of tags, triggers or anything else (just like other CIs offer)

**Comment by elgohr** [comment] 2019-10-18 17:57
Sounds good to me. I would prefer to either use `latest` on default and use `release_name` when turned on.

**Comment by turbo** [comment] 2019-10-18 18:14
> Sounds good to me. I would prefer to either use latest on default and use release_name when turned on.

Sound good, though I might be misinterpreting it. Could you please draw up a small table with examples?

**Comment by elgohr** [comment] 2019-10-18 19:46
| Types        | Tags                  |
|--------------|-----------------------|
| Tag/Release          | latest or {release/branch-name} |
| Branch       | {GITHUB_SHA}         |
| Pull Request | {GITHUB_SHA}         |

**Comment by turbo** [comment] 2019-10-18 19:54
That looks perfect. Whether there should be a way to (optionally) enable both for the "Tag/Release" case, I don't have a strong opinion on, but it might be important to other people's workflow.

**Comment by elgohr** [comment] 2019-10-18 20:08
Please see https://github.com/elgohr/Publish-Docker-Github-Action#tag_names
https://github.com/elgohr/Publish-Docker-Github-Action/releases/tag/2.7

**Comment by elgohr** [comment] 2019-10-19 15:33
Can we close this?

**Closed** 2019-10-22 22:04 UTC
